export const ALL_ARTICLES = [
  {
    category: "Pendidikan",
    slug: "dito-podium-olimpiade",
    image: "/panti.jpg",
    title: "Dito, dari panti asuhan ke podium olimpiade sains",
    desc: "Kisah inspiratif Dito yang berhasil meraih medali emas meskipun tumbuh dengan keterbatasan fasilitas belajar.",
    date: "28 Agustus 2026",
  },
  {
    category: "Kesehatan",
    slug: "pemeriksaan-gizi-2026",
    image: "/panti.jpg",
    title: "Pemeriksaan gizi rutin: 94% anak asuh kondisi prima",
    desc: "Tim medis melakukan pengecekan berkala untuk memastikan tumbuh kembang anak-anak berjalan optimal.",
    date: "26 Juli 2026",
  },
  {
    category: "Prestasi",
    slug: "juara-pencak-silat",
    image: "/panti.jpg",
    title: "Tim Pencak Silat Panti raih Juara Umum di Kejurda",
    desc: "Latihan keras setiap sore membuahkan hasil manis dengan perolehan 5 medali emas dan 2 perak.",
    date: "15 Juni 2026",
  },
  {
    category: "Donasi",
    slug: "laporan-dana-sosial",
    image: "/panti.jpg",
    title: "Laporan penyaluran dana donasi semester 1 2026",
    desc: "Transparansi adalah kunci. Simak rincian alokasi dana untuk operasional dan pendidikan anak-anak.",
    date: "10 Juni 2026",
  },
  {
    category: "Pendidikan",
    slug: "beasiswa-kuliah-sari",
    image: "/panti.jpg",
    title: "Sari lulus SNBT dengan beasiswa penuh di Universitas Indonesia",
    desc: "Satu lagi anak asuh kami yang membuktikan bahwa mimpi besar bisa dicapai dengan ketekunan.",
    date: "05 Juni 2026",
  },
  {
    category: "Kesehatan",
    slug: "vaksinasi-booster",
    image: "/panti.jpg",
    title: "Program vaksinasi booster untuk seluruh penghuni panti",
    desc: "Menjaga daya tahan tubuh anak-anak dan pengasuh di tengah perubahan cuaca yang ekstrem.",
    date: "20 Mei 2026",
  },
];
